// 1:36:29
// REST API TESTING FILE

// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Putri",
    "email": "putri@gmail.com",
    "password": "qwerty",
    "confirmPassword": "qwerty",
    "role": "user"
}


###
// Get All Users
GET http://localhost:5000/users


###
// Get Specific User
GET http://localhost:5000/users/ffe94236-0dab-4e5d-b3d7-42a92841fa33


###
// Update a User
PATCH  http://localhost:5000/users/f8e61152-5fc9-45f7-9b30-91b47d4ace14
Content-Type: application/json

{
    "name": "Iriansyah Syam Updated",
    "email": "iriansyahsyam@gmail.com",
    "password": "654321",
    "confirmPassword": "654321",
    "role": "user"
}

###
// Delete a User
DELETE  http://localhost:5000/users/f8e61152-5fc9-45f7-9b30-91b47d4ace14


### Admin
// Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "mchdarmawan@gmail.com",
    "password": "123456"
}

### User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "syam7@gmail.com",
    "password": "987654"
}


###
// Get logged data
GET  http://localhost:5000/me

###
// Logout
DELETE   http://localhost:5000/logout



###################### PRODUCT ######################

###
// Get all Product
GET http://localhost:5000/products


###
// Get single Product
GET http://localhost:5000/products/6786619c-20af-4177-923d-780b9f5e3d00
// data admin 6786619c-20af-4177-923d-780b9f5e3d00
// data user 8a759df3-b006-439a-a644-5921e9beceeb

###
// Create a Product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product 6",
    "price": 75000
}

###
// Update a Product
PATCH http://localhost:5000/products/6786619c-20af-4177-923d-780b9f5e3d00
Content-Type: application/json

{
    "name": "Product 1 admin",
    "price": 95000
}


###
// Delete product
DELETE http://localhost:5000/products/7d4ba2a1-109d-4bd7-9feb-af1b567e9b8c